### ISSUE TITLE
lazyloading with onExpand: Children's expanded keys are not cleared when the parent is collapsed

### ISSUE THREAD

**Issue by pvs560** [react-component/tree#47]
if children's are in expanded state and collapse parent then again expand the parent, still  the children's are in expanded state but it should be in closed state.

**Comment by cnatis** [comment]
I want to add also if I have nested keys, lets say a, ab, abc all expanded, then I collapse a and re-expand it. Without lazy loading the tree will expand to the last state before the collapse (a, ab, abc all expanded), with lazy loading it will only expand the one level (a, ab expanded but children not showing) my data is available already in this case and it's in the react virtual DOM I would expect either (a expanded, ab collapsed) or (a, ab, abc all expanded).

I understand this is likely because if we are lazy loading we might not have the data available, in that case though the children should be collapsed instead of displaying as expanded (I have to collapse and re-expand to see my data) or even better if we have the data in the virtual DOM we should try and render it.

**Comment by yesmeck** [comment]
Hello @pvs560 , I think this is by design.

**Comment by cnatis** [comment]
@yesmeck I believe my issue still stands even if the original issue is expected. In particular the part about having to collapse and re-expand a node to see the data.

**Comment by benjycui** [comment]
@cnatis I think it works fine now, if you still meet this problem, please file another issue and provide re-producible online demo, thanks.

ref: http://react-component.github.io/tree/examples/dynamic.html

<img src="http://g.recordit.co/mbRpNfJR8t.gif" />

**Comment by ashking** [comment]
I've the same issue too:

here;s the snippet:

**please not am setting the expanded keys via component state**

```
<Tree
    showLine
    showIcon={false}
     expandedKeys={this.state.expandedKeys}
     onExpand={this.onTreeItemExpand.bind(this)}
>
<--all the nested tree nodes -->
</Tree>
```

and 

```
onTreeItemExpand(info, e) {
    this.props.objBrowserexpandedKeys({ expandedKeys: info });
}
```

The parent node does not collapse unless all the child nodes are closed. 

Kindly help. Thanks
